[project]
name = "langchainv2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Aashish Jha", email = "aashishjhaoff@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "bs4>=0.0.2",
    "chromadb>=1.5.9",
    "faiss-cpu>=1.15.0",
    "fastapi>=0.141.1",
    "ipykernel>=7.3.0",
    "langchain>=1.3.17",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.2",
    "langchain-groq>=1.1.3",
    "langchain-huggingface>=1.2.2",
    "langchain-ollama>=1.1.0",
    "langchain-openai>=1.6.0",
    "langchain-openrouter>=0.2.8",
    "langchain-text-splitters>=1.1.2",
    "langserve>=0.3.3",
    "pypdf>=6.16.2",
    "python-dotenv>=1.2.3",
    "sentence-transformers>=6.0.0",
    "sse-starlette>=3.4.8",
    "streamlit>=1.62.0",
    "transformers>=5.15.1",
    "uvicorn>=0.52.4",
]

[project.scripts]
langchainv2 = "langchainv2:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
